<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect([
            ['name' => 'Vitaminas', 'slug' => 'vitaminas', 'icon_class' => 'bi-capsule-pill', 'sort_order' => 10],
            ['name' => 'Suplementos', 'slug' => 'suplementos', 'icon_class' => 'bi-prescription2', 'sort_order' => 20],
            ['name' => 'Snacks saludables', 'slug' => 'snacks-saludables', 'icon_class' => 'bi-basket2', 'sort_order' => 30],
            ['name' => 'Superfoods', 'slug' => 'superfoods', 'icon_class' => 'bi-flower1', 'sort_order' => 40],
            ['name' => 'Proteinas', 'slug' => 'proteinas', 'icon_class' => 'bi-egg-fried', 'sort_order' => 50],
            ['name' => 'Belleza natural', 'slug' => 'belleza-natural', 'icon_class' => 'bi-droplet', 'sort_order' => 60],
            ['name' => 'Infusiones', 'slug' => 'infusiones', 'icon_class' => 'bi-cup-hot', 'sort_order' => 70],
            ['name' => 'Para ninos', 'slug' => 'para-ninos', 'icon_class' => 'bi-emoji-smile', 'sort_order' => 80],
        ])->mapWithKeys(function (array $category) {
            $model = Category::updateOrCreate(
                ['slug' => $category['slug']],
                [
                    'name' => $category['name'],
                    'description' => 'Seleccion de '.$category['name'].' para una rutina saludable.',
                    'image_url' => null,
                    'icon_class' => $category['icon_class'],
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => $category['sort_order'],
                ]
            );

            return [$category['slug'] => $model];
        });

        $brands = collect([
            ['name' => 'Nutrex Peru', 'slug' => 'nutrex-peru', 'sort_order' => 10],
            ['name' => 'Amazonia Harvest', 'slug' => 'amazonia-harvest', 'sort_order' => 20],
            ['name' => 'Good Nature', 'slug' => 'good-nature', 'sort_order' => 30],
            ['name' => 'Nativa Organics', 'slug' => 'nativa-organics', 'sort_order' => 40],
            ['name' => 'Andean Naturals', 'slug' => 'andean-naturals', 'sort_order' => 50],
            ['name' => 'Bio Energy', 'slug' => 'bio-energy', 'sort_order' => 60],
        ])->mapWithKeys(function (array $brand) {
            $model = Brand::updateOrCreate(
                ['slug' => $brand['slug']],
                [
                    'name' => $brand['name'],
                    'logo_url' => null,
                    'is_active' => true,
                    'sort_order' => $brand['sort_order'],
                ]
            );

            return [$brand['slug'] => $model];
        });

        $products = [
            [
                'category' => 'suplementos',
                'brand' => 'good-nature',
                'name' => 'Omega 3 Premium',
                'slug' => 'omega-3-premium',
                'sku' => 'VN-OMEGA-120',
                'short_description' => '120 capsulas',
                'description' => 'Aceite de pescado de alta pureza con EPA y DHA. Apoya la salud del corazon, cerebro y articulaciones.',
                'benefits' => 'Apoya la salud cardiovascular. Contribuye al bienestar cerebral. Ayuda a mantener una rutina antiinflamatoria.',
                'ingredients' => 'Aceite de pescado purificado, gelatina, glicerina y agua purificada.',
                'usage_instructions' => 'Tomar 1 capsula al dia con alimentos, salvo indicacion profesional.',
                'price' => 79.90,
                'compare_at_price' => 89.90,
                'stock' => 45,
                'rating_average' => 4.8,
                'reviews_count' => 73,
                'is_featured' => true,
                'images' => [
                    'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80',
                    'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=900&q=80',
                ],
            ],
            [
                'category' => 'superfoods',
                'brand' => 'andean-naturals',
                'name' => 'Maca negra en polvo',
                'slug' => 'maca-negra-en-polvo',
                'sku' => 'VN-MACA-200',
                'short_description' => '200 g',
                'description' => 'Maca negra peruana en polvo, ideal para batidos, avenas y preparaciones energeticas.',
                'benefits' => 'Aporta energia natural. Complementa rutinas deportivas. Producto de origen andino.',
                'ingredients' => 'Maca negra gelatinizada en polvo.',
                'usage_instructions' => 'Agregar 1 cucharadita a batidos, jugos o desayunos.',
                'price' => 34.90,
                'compare_at_price' => null,
                'stock' => 28,
                'rating_average' => 4.7,
                'reviews_count' => 96,
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'snacks-saludables',
                'brand' => 'nativa-organics',
                'name' => 'Mix de frutos secos',
                'slug' => 'mix-de-frutos-secos',
                'sku' => 'VN-MIX-250',
                'short_description' => '250 g',
                'description' => 'Mezcla de almendras, cashews, pecanas y pasas para snacks de media manana.',
                'benefits' => 'Fuente de grasas buenas. Snack practico. Sin azucar anadida.',
                'ingredients' => 'Almendras, cashews, pecanas, pasas y semillas.',
                'usage_instructions' => 'Consumir como snack o agregar a yogurt y bowls.',
                'price' => 26.90,
                'compare_at_price' => null,
                'stock' => 32,
                'rating_average' => 4.5,
                'reviews_count' => 88,
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'proteinas',
                'brand' => 'bio-energy',
                'name' => 'Proteina vegetal vainilla',
                'slug' => 'proteina-vegetal-vainilla',
                'sku' => 'VN-PROT-500',
                'short_description' => '500 g',
                'description' => 'Proteina vegetal sabor vainilla, formulada para complementar rutinas activas.',
                'benefits' => 'Aporta proteina vegetal. Ideal post entrenamiento. Sabor suave.',
                'ingredients' => 'Proteina de arveja, arroz integral, sabor natural de vainilla.',
                'usage_instructions' => 'Mezclar una porcion con agua, bebida vegetal o batido.',
                'price' => 89.90,
                'compare_at_price' => null,
                'stock' => 18,
                'rating_average' => 4.8,
                'reviews_count' => 61,
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'vitaminas',
                'brand' => 'nutrex-peru',
                'name' => 'Vitamina C 1000 mg',
                'slug' => 'vitamina-c-1000-mg',
                'sku' => 'VN-VITC-60',
                'short_description' => '60 tabletas',
                'description' => 'Vitamina C de alta potencia para apoyo diario del sistema inmune.',
                'benefits' => 'Apoya defensas. Contribuye a la formacion de colageno. Antioxidante.',
                'ingredients' => 'Acido ascorbico, celulosa microcristalina.',
                'usage_instructions' => 'Tomar 1 tableta al dia con agua.',
                'price' => 59.00,
                'compare_at_price' => 69.90,
                'stock' => 60,
                'rating_average' => 4.9,
                'reviews_count' => 120,
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'superfoods',
                'brand' => 'amazonia-harvest',
                'name' => 'Aguaymanto deshidratado',
                'slug' => 'aguaymanto-deshidratado',
                'sku' => 'VN-AGUA-200',
                'short_description' => '200 g',
                'description' => 'Aguaymanto peruano deshidratado, practico para snacks y reposteria saludable.',
                'benefits' => 'Fuente de fibra. Sabor dulce-acido natural. Snack de origen peruano.',
                'ingredients' => 'Aguaymanto deshidratado.',
                'usage_instructions' => 'Consumir directo o agregar a granolas y postres.',
                'price' => 18.90,
                'compare_at_price' => null,
                'stock' => 40,
                'rating_average' => 4.3,
                'reviews_count' => 37,
                'is_featured' => true,
                'images' => ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'suplementos',
                'brand' => 'good-nature',
                'name' => 'Magnesio citrato',
                'slug' => 'magnesio-citrato',
                'sku' => 'VN-MAG-120',
                'short_description' => '120 capsulas',
                'description' => 'Magnesio citrato para apoyo muscular y bienestar diario.',
                'benefits' => 'Apoya funcion muscular. Complementa descanso. Facil absorcion.',
                'ingredients' => 'Citrato de magnesio, capsula vegetal.',
                'usage_instructions' => 'Tomar 1 capsula por la noche o segun recomendacion.',
                'price' => 49.90,
                'compare_at_price' => 59.90,
                'stock' => 22,
                'rating_average' => 4.6,
                'reviews_count' => 47,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'suplementos',
                'brand' => 'nutrex-peru',
                'name' => 'Zinc 25 mg',
                'slug' => 'zinc-25-mg',
                'sku' => 'VN-ZINC-100',
                'short_description' => '100 tabletas',
                'description' => 'Zinc en tabletas para apoyo inmune y cuidado de la piel.',
                'benefits' => 'Apoya defensas. Contribuye al cuidado de piel, cabello y unas.',
                'ingredients' => 'Zinc, celulosa microcristalina.',
                'usage_instructions' => 'Tomar 1 tableta al dia con alimentos.',
                'price' => 26.90,
                'compare_at_price' => null,
                'stock' => 34,
                'rating_average' => 4.4,
                'reviews_count' => 31,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'suplementos',
                'brand' => 'nativa-organics',
                'name' => 'Colageno hidrolizado',
                'slug' => 'colageno-hidrolizado',
                'sku' => 'VN-COLA-200',
                'short_description' => 'Sobre 200 g',
                'description' => 'Colageno hidrolizado en polvo para complementar rutinas de belleza y articulaciones.',
                'benefits' => 'Apoya piel y articulaciones. Facil de mezclar. Sabor neutro.',
                'ingredients' => 'Peptidos de colageno hidrolizado.',
                'usage_instructions' => 'Mezclar una porcion en agua, cafe o batido.',
                'price' => 69.90,
                'compare_at_price' => null,
                'stock' => 16,
                'rating_average' => 4.5,
                'reviews_count' => 55,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'suplementos',
                'brand' => 'bio-energy',
                'name' => 'Ashwagandha',
                'slug' => 'ashwagandha',
                'sku' => 'VN-ASH-60',
                'short_description' => '60 capsulas',
                'description' => 'Extracto de ashwagandha para apoyo al equilibrio diario.',
                'benefits' => 'Ayuda a manejar el estres. Complementa descanso. Adaptogeno natural.',
                'ingredients' => 'Extracto de ashwagandha, capsula vegetal.',
                'usage_instructions' => 'Tomar 1 capsula al dia.',
                'price' => 51.90,
                'compare_at_price' => 64.90,
                'stock' => 12,
                'rating_average' => 4.7,
                'reviews_count' => 24,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'vitaminas',
                'brand' => 'nutrex-peru',
                'name' => 'Vitamina D3 2000 UI',
                'slug' => 'vitamina-d3-2000-ui',
                'sku' => 'VN-D3-90',
                'short_description' => '90 capsulas',
                'description' => 'Vitamina D3 para apoyo oseo e inmune.',
                'benefits' => 'Apoya salud osea. Complementa exposicion solar baja.',
                'ingredients' => 'Colecalciferol, aceite vegetal, capsula blanda.',
                'usage_instructions' => 'Tomar 1 capsula al dia con alimentos.',
                'price' => 49.90,
                'compare_at_price' => null,
                'stock' => 38,
                'rating_average' => 4.8,
                'reviews_count' => 42,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'vitaminas',
                'brand' => 'good-nature',
                'name' => 'Complejo B',
                'slug' => 'complejo-b',
                'sku' => 'VN-CB-100',
                'short_description' => '100 tabletas',
                'description' => 'Complejo de vitaminas B para energia y metabolismo.',
                'benefits' => 'Apoya metabolismo energetico. Complementa rutinas activas.',
                'ingredients' => 'Vitaminas B1, B2, B3, B6, B12, acido folico.',
                'usage_instructions' => 'Tomar 1 tableta al dia.',
                'price' => 42.90,
                'compare_at_price' => null,
                'stock' => 48,
                'rating_average' => 4.4,
                'reviews_count' => 48,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'infusiones',
                'brand' => 'amazonia-harvest',
                'name' => 'Infusion relax natural',
                'slug' => 'infusion-relax-natural',
                'sku' => 'VN-INF-RELAX',
                'short_description' => '20 sobres',
                'description' => 'Mezcla herbal para una pausa relajante al final del dia.',
                'benefits' => 'Aroma suave. Ideal para la noche. Sin cafeina.',
                'ingredients' => 'Manzanilla, toronjil, cedron y lavanda.',
                'usage_instructions' => 'Infusionar 1 sobre en agua caliente por 5 minutos.',
                'price' => 22.90,
                'compare_at_price' => null,
                'stock' => 35,
                'rating_average' => 4.6,
                'reviews_count' => 19,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'belleza-natural',
                'brand' => 'nativa-organics',
                'name' => 'Aceite de coco organico',
                'slug' => 'aceite-de-coco-organico',
                'sku' => 'VN-COCO-250',
                'short_description' => '250 ml',
                'description' => 'Aceite de coco organico multiproposito para cocina y cuidado personal.',
                'benefits' => 'Uso culinario y cosmetico. Aroma natural. Prensado en frio.',
                'ingredients' => 'Aceite de coco organico.',
                'usage_instructions' => 'Usar en preparaciones o aplicar externamente segun necesidad.',
                'price' => 31.90,
                'compare_at_price' => null,
                'stock' => 21,
                'rating_average' => 4.5,
                'reviews_count' => 33,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80'],
            ],
            [
                'category' => 'para-ninos',
                'brand' => 'bio-energy',
                'name' => 'Gomitas de vitamina C',
                'slug' => 'gomitas-de-vitamina-c',
                'sku' => 'VN-GOM-C',
                'short_description' => '60 gomitas',
                'description' => 'Gomitas con vitamina C pensadas para complementar la rutina de los mas pequenos.',
                'benefits' => 'Formato agradable. Apoyo inmune. Sabor frutal.',
                'ingredients' => 'Vitamina C, pectina, sabor natural.',
                'usage_instructions' => 'Seguir indicacion del envase o profesional de salud.',
                'price' => 39.90,
                'compare_at_price' => null,
                'stock' => 26,
                'rating_average' => 4.7,
                'reviews_count' => 28,
                'is_featured' => false,
                'images' => ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80'],
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::updateOrCreate(
                ['slug' => $productData['slug']],
                [
                    'category_id' => $categories[$productData['category']]->id,
                    'brand_id' => $brands[$productData['brand']]->id,
                    'name' => $productData['name'],
                    'sku' => $productData['sku'],
                    'short_description' => $productData['short_description'],
                    'description' => $productData['description'],
                    'benefits' => $productData['benefits'],
                    'ingredients' => $productData['ingredients'],
                    'usage_instructions' => $productData['usage_instructions'],
                    'price' => $productData['price'],
                    'compare_at_price' => $productData['compare_at_price'],
                    'stock' => $productData['stock'],
                    'rating_average' => $productData['rating_average'],
                    'reviews_count' => $productData['reviews_count'],
                    'is_active' => true,
                    'is_featured' => $productData['is_featured'],
                    'published_at' => now()->subDays(rand(1, 40)),
                ]
            );

            $product->images()->delete();

            foreach (Arr::wrap($productData['images']) as $index => $imageUrl) {
                $product->images()->create([
                    'url' => $imageUrl,
                    'alt_text' => $product->name,
                    'is_primary' => $index === 0,
                    'sort_order' => $index + 1,
                ]);
            }
        }
    }
}
